'use client';

import React, { useState } from 'react';
import { FinalVerdict } from '@/types/session';
import { getPersonaById, COUNCIL_MEMBERS } from '@/lib/council/personas';
import {
  CheckCircle2,
  AlertTriangle,
  Copy,
  Check,
  Download,
  Share2,
  Sparkles,
  ShieldAlert,
} from 'lucide-react';

interface FinalVerdictCardProps {
  verdict: FinalVerdict;
  query: string;
}

export function FinalVerdictCard({ verdict, query }: FinalVerdictCardProps) {
  const [copied, setCopied] = useState(false);

  const isUnanimous = verdict.isUnanimous;

  const copyToClipboard = () => {
    const md = generateMarkdownExport();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadMarkdown = () => {
    const md = generateMarkdownExport();
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `council-verdict-${Date.now()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const generateMarkdownExport = (): string => {
    return `# The Council: Deliberation Verdict

**Subject:** ${query}  
**Date:** ${new Date(verdict.completedAt).toLocaleString()}  
**Status:** ${verdict.status.replace(/_/g, ' ')} (${verdict.isUnanimous ? 'Unanimous Consensus' : 'Consensus Not Fully Reached'})  
**Deliberation Rounds:** ${verdict.totalRoundsDeliberated}  
**Calls Executed:** ${verdict.totalCallsUsed}  

---

## 🏛️ Final Conclusion
${verdict.actionableConclusion}

---

## 🔑 Key Pillars of Justification
${verdict.keySupportingReasons.map((r, i) => `${i + 1}. ${r}`).join('\n')}

---

## ⚠️ Critical Caveats & Boundary Limits
${verdict.criticalCaveatsAndRisks.map((c, i) => `- ${c}`).join('\n')}

${
  verdict.survivingObjections.length > 0
    ? `\n---\n\n## 🛑 Surviving Objections (Honesty Rule Activated)\n${verdict.survivingObjections
        .map(
          (o) =>
            `- **${getPersonaById(o.personaId).name}:** ${o.objectionText}\n  *Principle:* ${o.irreconcilablePrinciple}`
        )
        .join('\n')}\n`
    : ''
}
---

## 🔄 How Views Shifted (Trajectory Summary)
${COUNCIL_MEMBERS.map((m) => `- **${m.name}:** ${verdict.personaShiftSummaries[m.id] || 'N/A'}`).join('\n')}

---
*Generated by The Council autonomous multi-agent deliberation chamber.*
`;
  };

  return (
    <section
      aria-label="Final Council Verdict"
      className={`w-full rounded-2xl border p-6 sm:p-8 backdrop-blur-md shadow-lg transition-smooth ${
        isUnanimous
          ? 'border-indigo-200 dark:border-indigo-900/80 bg-gradient-to-b from-indigo-50/40 via-white/80 to-white/95 dark:from-indigo-950/20 dark:via-gray-900/60 dark:to-gray-900/90 council-glow'
          : 'border-amber-200 dark:border-amber-900/80 bg-gradient-to-b from-amber-50/40 via-white/80 to-white/95 dark:from-amber-950/20 dark:via-gray-900/60 dark:to-gray-900/90'
      }`}
    >
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-5 border-b border-gray-200/80 dark:border-gray-800 gap-4">
        <div className="flex items-center gap-3">
          <div
            className={`w-10 h-10 rounded-xl flex items-center justify-center font-bold text-white shadow-md ${
              isUnanimous
                ? 'bg-gradient-to-tr from-emerald-600 to-indigo-600'
                : 'bg-gradient-to-tr from-amber-600 to-red-600'
            }`}
          >
            {isUnanimous ? (
              <CheckCircle2 className="w-5 h-5" />
            ) : (
              <ShieldAlert className="w-5 h-5" />
            )}
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[11px] uppercase font-mono tracking-wider text-indigo-600 dark:text-indigo-400 font-semibold block">
                Deliberation Concluded
              </span>
            </div>
            <div className="flex items-center gap-2 mt-0.5">
              <h2 className="font-serif font-bold text-lg sm:text-xl text-gray-900 dark:text-gray-100">
                {isUnanimous ? 'Unanimous Consensus Reached' : 'Consensus Not Fully Reached'}
              </h2>
              <span
                className={`text-[10px] font-mono font-semibold px-2.5 py-0.5 rounded-full uppercase tracking-wider ${
                  isUnanimous
                    ? 'bg-emerald-100 dark:bg-emerald-950/80 text-emerald-800 dark:text-emerald-300'
                    : 'bg-amber-100 dark:bg-amber-950/80 text-amber-800 dark:text-amber-300'
                }`}
              >
                {verdict.status.replace(/_/g, ' ')}
              </span>
            </div>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Deliberated across {verdict.totalRoundsDeliberated} rounds &bull; {verdict.ratifiedBy.length} of 8 members ratified
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={copyToClipboard}
            className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-200 transition-smooth"
            title="Copy verdict to clipboard"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-500" />
                <span>Copied to Clipboard</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-gray-400" />
                <span>Copy Deliberation Summary</span>
              </>
            )}
          </button>

          <button
            onClick={downloadMarkdown}
            className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-200 transition-smooth"
            title="Download full Markdown report"
          >
            <Download className="w-3.5 h-3.5 text-gray-400" />
            <span>Export Markdown</span>
          </button>
        </div>
      </div>

      {/* Main Conclusion */}
      <div className="py-6 border-b border-gray-200/60 dark:border-gray-800/60">
        <h3 className="text-xs font-semibold uppercase tracking-wider text-gray-500 mb-1">
          Actionable Guidance & Unanimous Synthesis
        </h3>
        <p className="font-serif text-base sm:text-lg text-gray-900 dark:text-gray-100 leading-relaxed font-medium">
          {verdict.actionableConclusion}
        </p>
      </div>

      {/* Supporting Reasons & Critical Caveats Grid */}
      <div className="py-6 border-b border-gray-200/60 dark:border-gray-800/60 grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <h4 className="text-xs font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400 mb-3 flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5" />
            Key Pillars of Agreement
          </h4>
          <ul className="space-y-2">
            {verdict.keySupportingReasons.map((reason, i) => (
              <li
                key={i}
                className="text-xs text-gray-700 dark:text-gray-300 flex items-start gap-2 leading-relaxed"
              >
                <span className="w-4 h-4 rounded-full bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5">
                  {i + 1}
                </span>
                <span>{reason}</span>
              </li>
            ))}
          </ul>
        </div>

        <div>
          <h4 className="text-xs font-semibold uppercase tracking-wider text-amber-600 dark:text-amber-400 mb-3 flex items-center gap-1.5">
            <AlertTriangle className="w-3.5 h-3.5" />
            Crucial Caveats & Boundary Conditions
          </h4>
          <ul className="space-y-2">
            {verdict.criticalCaveatsAndRisks.map((caveat, i) => (
              <li
                key={i}
                className="text-xs text-gray-700 dark:text-gray-300 flex items-start gap-2 leading-relaxed"
              >
                <span className="text-amber-500 font-bold shrink-0 mt-0.5">&bull;</span>
                <span>{caveat}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Surviving Objections Section (Honesty Rule) */}
      {!isUnanimous && verdict.survivingObjections.length > 0 && (
        <div className="py-6 border-b border-gray-200/60 dark:border-gray-800/60 bg-red-50/30 dark:bg-red-950/20 -mx-6 sm:-mx-8 px-6 sm:px-8">
          <h4 className="text-xs font-semibold uppercase tracking-wider text-red-600 dark:text-red-400 mb-2 flex items-center gap-1.5">
            <ShieldAlert className="w-3.5 h-3.5" />
            Honesty Rule: Unresolved Dissenting Objections
          </h4>
          <p className="text-xs text-gray-600 dark:text-gray-400 mb-3">
            In accordance with council constitutional rules, agreement is never fabricated. The following members maintained formal objections:
          </p>
          <div className="space-y-2">
            {verdict.survivingObjections.map((obj, i) => {
              const persona = getPersonaById(obj.personaId);
              return (
                <div
                  key={i}
                  className="p-3 rounded-lg border border-red-200 dark:border-red-900/60 bg-white/70 dark:bg-gray-900/60 text-xs"
                >
                  <span className="font-serif font-bold text-red-700 dark:text-red-300">
                    {persona.name}:
                  </span>{' '}
                  <span className="text-gray-800 dark:text-gray-200">{obj.objectionText}</span>
                  {obj.irreconcilablePrinciple && (
                    <p className="mt-1 text-[11px] text-gray-500 dark:text-gray-400 italic">
                      Principle: {obj.irreconcilablePrinciple}
                    </p>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* How Views Shifted Panel */}
      <div className="pt-6">
        <h4 className="text-xs font-semibold uppercase tracking-wider text-gray-500 mb-3">
          How Personas&apos; Views Shifted
        </h4>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {COUNCIL_MEMBERS.map((member) => {
            const shiftText = verdict.personaShiftSummaries[member.id];
            if (!shiftText) return null;

            const hasStartedAt = shiftText.includes('Started at');
            const hasShiftedTo = shiftText.includes('Shifted to');

            return (
              <div
                key={member.id}
                className="p-3 rounded-lg border border-gray-100 dark:border-gray-800 bg-white/50 dark:bg-gray-900/30 text-xs space-y-2"
              >
                <div className="flex items-center gap-2 mb-1">
                  <div
                    className="w-2.5 h-2.5 rounded-full shrink-0"
                    style={{ backgroundColor: member.colorHex }}
                  />
                  <span className="font-serif font-semibold text-gray-900 dark:text-gray-100">
                    {member.name}
                  </span>
                  <span className="text-[10px] text-gray-400">({member.title})</span>
                </div>

                {hasStartedAt && hasShiftedTo ? (
                  <div className="space-y-1.5 text-[11px] leading-relaxed">
                    <div>
                      <span className="font-semibold text-gray-500 uppercase text-[10px] tracking-wider block">
                        Initial Stance
                      </span>
                      <p className="text-gray-600 dark:text-gray-400 italic">
                        {shiftText.split('. Shifted to')[0]}
                      </p>
                    </div>
                    <div>
                      <span className="font-semibold text-indigo-600 dark:text-indigo-400 uppercase text-[10px] tracking-wider block">
                        Final Stance
                      </span>
                      <p className="text-gray-800 dark:text-gray-200">
                        Shifted to {shiftText.split('. Shifted to')[1]}
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-1 text-[11px] leading-relaxed">
                    <div>
                      <span className="font-semibold text-gray-500 uppercase text-[10px] tracking-wider block">
                        Initial Stance
                      </span>
                      <p className="text-gray-600 dark:text-gray-400 italic">
                        Initial position recorded during opening round.
                      </p>
                    </div>
                    <div>
                      <span className="font-semibold text-indigo-600 dark:text-indigo-400 uppercase text-[10px] tracking-wider block">
                        Final Stance
                      </span>
                      <p className="text-gray-800 dark:text-gray-200">{shiftText}</p>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
