'use client';

import React, { useState } from 'react';
import { FinalVerdict } from '@/types/session';
import { findPersonaById, COUNCIL_MEMBERS } from '@/lib/council/personas';
import {
  CheckCircle2,
  AlertTriangle,
  Copy,
  Check,
  Download,
  Sparkles,
  ShieldAlert,
  Compass,
} from 'lucide-react';
import { GlassCard } from '@/components/ui/GlassCard';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { useToast } from '@/components/ui/Toast';

interface FinalVerdictCardProps {
  verdict: FinalVerdict;
  query: string;
}

export function FinalVerdictCard({ verdict, query }: FinalVerdictCardProps) {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const isUnanimous = verdict.isUnanimous;

  const copyToClipboard = () => {
    const md = generateMarkdownExport();
    navigator.clipboard.writeText(md);
    setCopied(true);
    toast({
      type: 'success',
      title: 'Deliberation Summary Copied',
      description: 'The deliberation synthesis and persona trajectories are in your clipboard.',
    });
    setTimeout(() => setCopied(false), 2500);
  };

  const downloadMarkdown = () => {
    const md = generateMarkdownExport();
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `council-verdict-${Date.now()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast({
      type: 'info',
      title: 'Report Exported',
      description: 'The markdown verdict report has been downloaded.',
    });
  };

  const generateMarkdownExport = (): string => {
    return `# The Council: Deliberation Verdict

**Subject:** ${query}  
**Date:** ${new Date(verdict.completedAt).toLocaleString()}  
**Status:** ${verdict.status.replace(/_/g, ' ')} (${verdict.isUnanimous ? 'Unanimous Consensus' : 'Consensus Not Fully Reached'})  
**Deliberation Rounds:** ${verdict.totalRoundsDeliberated}  
**Calls Executed:** ${verdict.totalCallsUsed}  

---

## 🏛️ Final Verdict
**${verdict.verdictOneLiner || (verdict.actionableConclusion ? verdict.actionableConclusion.split(/[.!?]/)[0] + '.' : 'Verdict concluded.')}**

${verdict.actionableConclusion || ''}

---

## 🔑 Key Pillars of Justification
${(verdict.keySupportingReasons ?? []).map((r, i) => `${i + 1}. ${r}`).join('\n')}

---

## ⚠️ Critical Caveats & Boundary Limits
${(verdict.criticalCaveatsAndRisks ?? []).map((c) => `- ${c}`).join('\n')}

${
  (verdict.survivingObjections ?? []).length > 0
    ? `\n---\n\n## 🛑 Surviving Objections (Honesty Rule Activated)\n${(verdict.survivingObjections ?? [])
        .map(
          (o) =>
            `- **${findPersonaById(o.personaId)?.name ?? o.personaId}:** ${o.objectionText}\n  *Principle:* ${o.irreconcilablePrinciple}`
        )
        .join('\n')}\n`
    : ''
}
---

## 🔄 How Views Shifted (Trajectory Summary)
${COUNCIL_MEMBERS.map((m) => `- **${m.name}:** ${verdict.personaShiftSummaries[m.id] || 'N/A'}`).join('\n')}

---
*Generated by The Council autonomous multi-agent deliberation chamber.*
`;
  };

  return (
    <GlassCard
      as="section"
      aria-label="Final Council Verdict"
      variant="highlight"
      padded="lg"
      className={`w-full !rounded-[20px] transition-all animate-slide-up ${
        isUnanimous
          ? '!border-indigo-400/30 dark:!border-indigo-500/40 council-glow'
          : '!border-amber-400/30 dark:!border-amber-500/40'
      }`}
    >
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-5 border-b border-gray-200/70 dark:border-white/10 gap-4">
        <div className="flex items-center gap-3.5">
          <div
            className={`w-11 h-11 rounded-[14px] flex items-center justify-center font-bold text-white shadow-md shrink-0 border border-white/20 ${
              isUnanimous
                ? 'bg-gradient-to-tr from-emerald-600 via-indigo-600 to-indigo-500 shadow-indigo-500/20'
                : 'bg-gradient-to-tr from-amber-600 to-red-600 shadow-amber-500/20'
            }`}
          >
            {isUnanimous ? (
              <CheckCircle2 className="w-5 h-5 stroke-[2.2]" />
            ) : (
              <ShieldAlert className="w-5 h-5 stroke-[2.2]" />
            )}
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[11px] uppercase font-mono tracking-wider text-indigo-600 dark:text-indigo-400 font-semibold block">
                Deliberation Concluded
              </span>
            </div>
            <div className="flex flex-wrap items-center gap-2 mt-0.5">
              <h2 className="font-serif font-bold text-lg sm:text-xl text-gray-950 dark:text-gray-50 leading-tight">
                {isUnanimous ? 'Unanimous Consensus Reached' : 'Consensus Not Fully Reached'}
              </h2>
              <Badge
                variant={isUnanimous ? 'success' : 'warning'}
                size="xs"
              >
                {verdict.status.replace(/_/g, ' ')}
              </Badge>
            </div>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
              Deliberated across {verdict.totalRoundsDeliberated} rounds &bull; {(verdict.ratifiedBy ?? []).length} of 8 members ratified{isUnanimous ? ' unanimously' : ((verdict.survivingObjections ?? []).length > 0 ? ` (${(verdict.survivingObjections ?? []).length} reservation${(verdict.survivingObjections ?? []).length > 1 ? 's' : ''} noted)` : '')}
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2 self-start sm:self-auto">
          <Button
            variant="secondary"
            size="sm"
            onClick={copyToClipboard}
            leftIcon={copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5 text-gray-400" />}
            title="Copy verdict to clipboard"
          >
            {copied ? 'Copied to Clipboard' : 'Copy Deliberation Summary'}
          </Button>

          <Button
            variant="glass"
            size="sm"
            onClick={downloadMarkdown}
            leftIcon={<Download className="w-3.5 h-3.5 text-gray-400" />}
            title="Download full Markdown report"
          >
            Export Markdown
          </Button>
        </div>
      </div>

      {/* Main Conclusion / Unanimous Synthesis Section */}
      <div className="py-6 border-b border-gray-200/70 dark:border-white/10">
        <div className="flex items-center gap-2 mb-2">
          <Badge variant="accent" size="xs">
            {isUnanimous ? 'Unanimous Synthesis' : 'Deliberation Synthesis'}
          </Badge>
        </div>
        <h3
          className={`font-serif font-bold text-xl sm:text-2xl leading-snug mb-3 tracking-tight ${
            isUnanimous
              ? 'text-indigo-950 dark:text-indigo-200'
              : 'text-amber-950 dark:text-amber-200'
          }`}
        >
          {verdict.verdictOneLiner || (verdict.actionableConclusion ? verdict.actionableConclusion.split(/[.!?]/)[0] + '.' : 'Verdict concluded.')}
        </h3>
        
        <div className="mt-3 p-4 rounded-[14px] bg-white/60 dark:bg-white/[0.04] border border-gray-200/60 dark:border-white/10 backdrop-blur-md">
          <h4 className="text-xs font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400 mb-1.5 flex items-center gap-1.5">
            <Compass className="w-3.5 h-3.5" />
            Actionable Guidance
          </h4>
          <p className="text-sm text-gray-800 dark:text-gray-200 leading-relaxed font-sans">
            {verdict.actionableConclusion}
          </p>
        </div>
      </div>

      {/* Supporting Reasons & Critical Caveats Grid */}
      <div className="py-6 border-b border-gray-200/70 dark:border-white/10 grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <h4 className="text-xs font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400 mb-3 flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5" />
            Key Pillars of Agreement
          </h4>
          <ul className="space-y-2.5">
            {verdict.keySupportingReasons.map((reason, i) => (
              <li
                key={i}
                className="text-xs text-gray-800 dark:text-gray-200 flex items-start gap-2.5 leading-relaxed bg-white/40 dark:bg-white/[0.03] p-2.5 rounded-[10px] border border-gray-100 dark:border-white/5"
              >
                <span className="w-4 h-4 rounded-full bg-indigo-500/15 text-indigo-600 dark:text-indigo-400 text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5 border border-indigo-500/25">
                  {i + 1}
                </span>
                <span>{reason}</span>
              </li>
            ))}
          </ul>
        </div>

        <div>
          <h4 className="text-xs font-semibold uppercase tracking-wider text-amber-600 dark:text-amber-400 mb-3 flex items-center gap-1.5">
            <AlertTriangle className="w-3.5 h-3.5" />
            Crucial Caveats & Boundary Conditions
          </h4>
          <ul className="space-y-2.5">
            {verdict.criticalCaveatsAndRisks.map((caveat, i) => (
              <li
                key={i}
                className="text-xs text-gray-800 dark:text-gray-200 flex items-start gap-2.5 leading-relaxed bg-white/40 dark:bg-white/[0.03] p-2.5 rounded-[10px] border border-gray-100 dark:border-white/5"
              >
                <span className="text-amber-500 font-bold shrink-0 mt-0.5">&bull;</span>
                <span>{caveat}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Surviving Objections Section (Honesty Rule) */}
      {!isUnanimous && verdict.survivingObjections.length > 0 && (
        <div className="py-6 border-b border-gray-200/70 dark:border-white/10 bg-red-500/[0.04] -mx-6 sm:-mx-8 px-6 sm:px-8">
          <h4 className="text-xs font-semibold uppercase tracking-wider text-red-600 dark:text-red-400 mb-2 flex items-center gap-1.5">
            <ShieldAlert className="w-3.5 h-3.5" />
            Honesty Rule: Unresolved Reservations & Objections
          </h4>
          <p className="text-xs text-gray-600 dark:text-gray-400 mb-3">
            In accordance with council constitutional rules, agreement is never fabricated. The following members maintained formal reservations or objections:
          </p>
          <div className="space-y-2.5">
            {verdict.survivingObjections.map((obj, i) => {
              const persona = findPersonaById(obj.personaId);
              return (
                <div
                  key={i}
                  className="p-3.5 rounded-[12px] border border-red-500/25 bg-white/70 dark:bg-red-950/20 text-xs backdrop-blur-md"
                >
                  <span className="font-serif font-bold text-red-700 dark:text-red-300">
                    {persona ? persona.name : obj.personaId}:
                  </span>{' '}
                  <span className="text-gray-800 dark:text-gray-200">{obj.objectionText}</span>
                  {obj.irreconcilablePrinciple && (
                    <p className="mt-1.5 text-[11px] text-gray-500 dark:text-gray-400 italic">
                      Principle: {obj.irreconcilablePrinciple}
                    </p>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* How Views Shifted Panel */}
      <div className="pt-6">
        <h4 className="text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-3">
          How Personas&apos; Views Shifted
        </h4>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {COUNCIL_MEMBERS.map((member) => {
            const shiftText = verdict.personaShiftSummaries[member.id];
            if (!shiftText) return null;

            const hasStartedAt = shiftText.includes('Started at');
            const hasShiftedTo = shiftText.includes('Shifted to');

            return (
              <div
                key={member.id}
                className="p-3.5 rounded-[12px] border border-gray-200/60 dark:border-white/10 bg-white/50 dark:bg-white/[0.03] backdrop-blur-md text-xs space-y-2"
              >
                <div className="flex items-center gap-2 mb-1">
                  <div
                    className="w-2.5 h-2.5 rounded-full shrink-0"
                    style={{ backgroundColor: member.colorHex }}
                  />
                  <span className="font-serif font-bold text-gray-950 dark:text-gray-50">
                    {member.name}
                  </span>
                  <span className="text-[10px] text-gray-400">({member.title})</span>
                </div>

                {hasStartedAt && hasShiftedTo ? (
                  <div className="space-y-1.5 text-[11px] leading-relaxed">
                    <div>
                      <span className="font-semibold text-gray-400 uppercase text-[10px] tracking-wider block">
                        Initial Stance
                      </span>
                      <p className="text-gray-600 dark:text-gray-400 italic">
                        {shiftText.split('. Shifted to')[0]}
                      </p>
                    </div>
                    <div>
                      <span className="font-semibold text-indigo-600 dark:text-indigo-400 uppercase text-[10px] tracking-wider block">
                        Final Stance
                      </span>
                      <p className="text-gray-800 dark:text-gray-200 font-medium">
                        Shifted to {shiftText.split('. Shifted to')[1]}
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-1 text-[11px] leading-relaxed">
                    <div>
                      <span className="font-semibold text-gray-400 uppercase text-[10px] tracking-wider block">
                        Initial Stance
                      </span>
                      <p className="text-gray-600 dark:text-gray-400 italic">
                        Initial position recorded during opening round.
                      </p>
                    </div>
                    <div>
                      <span className="font-semibold text-indigo-600 dark:text-indigo-400 uppercase text-[10px] tracking-wider block">
                        Final Stance
                      </span>
                      <p className="text-gray-800 dark:text-gray-200 font-medium">{shiftText}</p>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </GlassCard>
  );
}
